name: 'wasm-bindgen-action'
description: 'Install `wasm-bindgen` by downloading the executable (much faster than `cargo install wasm-bindgen-cli`, seconds vs minutes).'
author: 'jetli'
inputs:
  version:
    description: 'Optional version of wasm-bindgen to install (eg. "0.2.68", "latest")'
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'orange'
